version: "3.8"

services:
  flask-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    volumes:
      - ./telemetry/collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
    command:
      ["--config=/etc/otelcol/config.yaml"]


