apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-py-svc
spec:
  type: NodePort
  selector:
    app: opentelemetry-py
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
